[theme]
primaryColor = "#1e90ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0d0d0d"
textColor = "#e0e0e0"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"
